
// Loop through all numbers from 1 to 100.


// for (let x = 1; x <= 100; x++){
//     console.log(x)
// }

// If a number is divisible by 3, log “Fizz.” 

for (let x = 1; x <= 100; x++){
    if (x % 3 === 0){
        console.log("Fizz");
    }
        console.log(x);}
      


// If a number is divisible by 5, log “Buzz.” 




// for (let x = 1; x <= 100; x++){
//     if (x % 3 === 0) {
//         console.log ("Fizz");}
//     else if (x % 5 === 0){
//         console.log("Buzz");}
//     else if (x % 3 && x % 5){
//         console.log("Fizz Buzz")}
//     else if (!x % 3 && x % 5){
//         console.log(x)
//     }
//      else {
//     console.log(x);
//     }
// }




// If a number is divisible by both 3 and 5, log “Fizz Buzz.”


// If a number is not divisible by either 3 or 5, log the number.


